"""017_add_payment_region_support

Revision ID: [autogenerated]
Revises: bf5e71d045a3
Create Date: [current date]

"""

from typing import Sequence, Union
from uuid import uuid4

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65b320fc1dfa"
down_revision: Union[str, None] = "bf5e71d045a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  # Add currency to billing plans (instead of region)
  op.add_column("billing_plans", sa.Column("currency", sa.String(3), nullable=False, server_default="USD"))

  # Rename amount_usd to amount in billing_plans table
  op.alter_column("billing_plans", "amount_usd", new_column_name="amount")

  # Rename amount_usd to amount in transactions table
  op.alter_column("transactions", "amount_usd", new_column_name="amount")

  # Add payment_provider to transactions
  op.add_column("transactions", sa.Column("payment_provider", sa.String(20), nullable=True))

  # Add Razorpay specific columns
  op.add_column("transactions", sa.Column("razorpay_payment_id", sa.String(), nullable=True))
  op.add_column("transactions", sa.Column("razorpay_customer_id", sa.String(), nullable=True))
  op.add_column("transactions", sa.Column("razorpay_invoice_id", sa.String(), nullable=True))

  # Set default payment_provider for existing transactions
  op.execute("UPDATE transactions SET payment_provider = 'stripe' WHERE payment_provider IS NULL")

  # Create INR plans with specific prices
  op.execute(f"""
    INSERT INTO billing_plans (id, name, amount, credits, discount_percentage, is_active, created_at, updated_at, currency)
    VALUES
    ('{str(uuid4())}', 'Basic', 99, 1000, 0.0, true, now(), now(), 'INR'),
    ('{str(uuid4())}', 'Standard', 399, 6000, 10.0, true, now(), now(), 'INR'),
    ('{str(uuid4())}', 'Premium', 799, 15000, 20.0, true, now(), now(), 'INR'),
    ('{str(uuid4())}', 'Enterprise', 1999, 50000, 35.0, true, now(), now(), 'INR')
  """)


def downgrade() -> None:
  # Delete INR currency plans
  op.execute("DELETE FROM billing_plans WHERE currency = 'INR'")

  # Drop Razorpay columns
  op.drop_column("transactions", "razorpay_invoice_id")
  op.drop_column("transactions", "razorpay_customer_id")
  op.drop_column("transactions", "razorpay_payment_id")

  # Drop columns
  op.drop_column("transactions", "payment_provider")

  # Rename amount back to amount_usd in billing_plans table
  op.alter_column("billing_plans", "amount", new_column_name="amount_usd")

  # Rename amount back to amount_usd in transactions table
  op.alter_column("transactions", "amount", new_column_name="amount_usd")

  # Drop currency column
  op.drop_column("billing_plans", "currency")
